### PR TITLE
fixed the ios build issue;

### PR DESCRIPTION
**Pull request by ashwinKashyapKrishna**
Fix for https://github.com/atlj/react-native-background-remover/issues/4

### CODE REVIEW

**Review by atlj — APPROVED** [review]
LGTM thanks for sending this!

**Comment by atlj** [comment]
Screenshot 2024-09-02 at 19 01 47
Hey it looks like the CI is failing. Could you take a look?

**Comment by ashwinKashyapKrishna** [comment]
Thanks for the response :)
Applied a fix, it built ok for the example project locally, maybe worth trying it with the CI once if thats ok

**Comment by charlemagneVI** [comment]
Is it possible to get this merged in? I think this issue blocks being able to use this package for iOS builds.

**Comment by atlj** [comment]
@charlemagneVI thanks so much for the ping. Releasing now

**Comment by atlj** [comment]
https://github.com/atlj/react-native-background-remover/releases/tag/0.3.2

**Pull request merged**
